# Generated by Django 5.1.7 on 2025-11-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('ingredients', models.JSONField(default=list, help_text='List of ingredients')),
                ('instructions', models.TextField()),
                ('picture_link', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(choices=[('ar', 'All Recipes'), ('epi', 'Epicurious'), ('fn', 'Food Network')], db_index=True, help_text='Source of the recipe', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipe_id'], name='recipes_rec_recipe__2f1c9a_idx'), models.Index(fields=['source'], name='recipes_rec_source_b6db08_idx'), models.Index(fields=['title'], name='recipes_rec_title_9ebae8_idx')],
            },
        ),
    ]
