# Generated by Django 5.2.9 on 2025-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_vegan',
            field=models.BooleanField(default=True),
        ),
    ]
