# Generated by Django 5.2.7 on 2025-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_is_vegan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='instruction',
            new_name='instruction_en',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_kz',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='instruction_kz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='instruction_ru',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_kz',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name_kz',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='name_ru',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
