# Generated by Django 5.2.7 on 2025-12-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_name_category_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ru', models.CharField(max_length=100, unique=True)),
                ('name_kz', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
